// export const UPDATE_COMPETITION_REQUEST = "UPDATE_COMPETITION_REQUEST";
// export const UPDATE_COMPETITION_SUCCESS = "UPDATE_COMPETITION_SUCCESS";
// export const UPDATE_COMPETITION_RESET = "UPDATE_COMPETITION_RESET";
// export const UPDATE_COMPETITION_FAIL = "UPDATE_COMPETITION_FAIL";

// export const DELETE_COMPETITION_REQUEST = "DELETE_COMPETITION_REQUEST";
// export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS";
// export const DELETE_COMPETITION_RESET = "DELETE_COMPETITION_RESET";
// export const DELETE_COMPETITION_FAIL = "DELETE_COMPETITION_FAIL";

export const COMPETITION_DETAILS_REQUEST = "COMPETITION_DETAILS_REQUEST";
export const COMPETITION_DETAILS_SUCCESS = "COMPETITION_DETAILS_SUCCESS";
export const COMPETITION_DETAILS_FAIL = "COMPETITION_DETAILS_FAIL";

// export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
// export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
// export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
// export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

// export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
// export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
// export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

// export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
// export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
// export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
// export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

